/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pratikum_Tugas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class GUI_LaporanBarang extends javax.swing.JFrame {

    /**
     * Creates new form GUI_LaporanBarang
     */
    public GUI_LaporanBarang() {
        initComponents();
        // mengambil model data dan menyimpan dalam objek default table model datamodel
        DefaultTableModel dataModel = (DefaultTableModel) tabel_data_laporanbarang.getModel();
        //mendapatkan jumlah baris yang ada dalam model data saat ini 
        int rowCount = dataModel.getRowCount();
        while (rowCount>0){
            // mengapus baris terakhir dari mode data
            dataModel.removeRow(rowCount - 1);
            // memperbaharui nilai rowcount setelah penghapusan baris terakhir
            rowCount = dataModel.getRowCount();
        }
    }
    public Connection conn;
     public void koneksi() throws SQLException {
        try {
            conn = null;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/OOP_2218136_tugas10?user=root&password=");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_LaporanBarang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException e) {
            Logger.getLogger(GUI_LaporanBarang.class.getName()).log(Level.SEVERE, null, e);
        } catch (Exception es) {
            Logger.getLogger(GUI_LaporanBarang.class.getName()).log(Level.SEVERE, null, es);
        }
    }
      public void refresh() {
        new GUI_LaporanBarang().setVisible(true);
        this.setVisible(false);
    }
       public void tampil() {
        DefaultTableModel tabelhead = new DefaultTableModel();
        tabelhead.addColumn("NamaBarang");
        tabelhead.addColumn("Pemasukkan awal");
        tabelhead.addColumn("Jumlah_Barang_keluar");
        tabelhead.addColumn("Total_Keseluruhan");
        tabelhead.addColumn("Data_barang");
        tabelhead.addColumn("data_total_barang");
        try {
            koneksi();
            String sql = "SELECT * FROM laporanadmin";
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while (res.next()) {
                tabelhead.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6),res.getString(7)});
            }
            tabel_data_laporanbarang.setModel(tabelhead);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "BELUM TERKONEKSI");
        }
    }
       
      public void insert() {
        String namaBarang = txtnamabarang.getText();
        String Pemasukkan = txtPemasukan.getText();
        String barangKeluar =  txtBarangKeluar.getText();
        String hargaBarang = txt_dataBarang.getText();
        String TotalKeseluruhan = txtTotal.getText();
        String Data_dari_gudang = txt_dataBarang.getText();
        String DataTotalBarang = txt_totaldata.getText();
        
        try {
            koneksi();
            Statement statement = conn.createStatement();
            statement.executeUpdate("INSERT INTO laporanadmin (NamaBarang, Pemasukkan_awal, Jumlah_Barang_keluar, Total_Keseluruhan,Data_barang,data_total_barang)"
                    + "VALUES('" + namaBarang + "','" + Pemasukkan + "','" + barangKeluar + "','" + hargaBarang + "','" + TotalKeseluruhan + "','" + Data_dari_gudang + "','" + DataTotalBarang + "')");
            statement.close();
            JOptionPane.showMessageDialog(null, "Berhasil Memasukan Data laporan admin!" + "\n" + namaBarang);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Input!");
        }
        refresh();
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTOTAL = new javax.swing.JButton();
        txtPemasukan = new javax.swing.JTextField();
        txtBarangKeluar = new javax.swing.JTextField();
        txtTotalPengeluaran = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data_laporanbarang = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_dataBarang = new javax.swing.JTextField();
        btnDATA = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_totaldata = new javax.swing.JTextField();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LAPORAN ADMIN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("JUMLAH BARANG KELUAR");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("PEMASUKAN AWAL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("TOTAL HARGA BARANG");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("TOTAL KESELURUHAN");

        btnTOTAL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTOTAL.setText("TOTAL");
        btnTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTOTALActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnLog.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLog.setText("LOG OUT");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("RP.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ton");

        btn_simpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        tabel_data_laporanbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NAMA BARANG", "Pemasukan awal", "Jumlah Barang Keluar", "Total harga barang", "Total keseluruhan", "DATA BARANG", "DATA TOTAL BARANG"
            }
        ));
        tabel_data_laporanbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_data_laporanbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_data_laporanbarang);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("NAMA BARANG ");

        txtnamabarang.setText(" ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("/ kw");

        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("DATA DARI GUDANG");

        btnDATA.setText("DATA");
        btnDATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDATAActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("DATA TOTAL BARANG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(34, 34, 34))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnamabarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalPengeluaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(txtPemasukan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBarangKeluar, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_totaldata, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_dataBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTOTAL)
                                    .addComponent(btnDATA))))))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(28, 28, 28)
                        .addComponent(btn_simpan)
                        .addGap(30, 30, 30)
                        .addComponent(btnhapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotalPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTOTAL))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnhapus)
                                .addComponent(btn_simpan)
                                .addComponent(btnClear)
                                .addComponent(btnLog))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txt_dataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_totaldata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDATA)
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTOTALActionPerformed
        // TODO add your handling code here:
        Pembayaran_kasir untung = new Pembayaran_kasir();
        untung.namaBarang = (txtnamabarang.getText());
        untung.barangmasuk = Double.parseDouble(txtPemasukan.getText());
        untung.barangKeluar= Double.parseDouble(txtBarangKeluar.getText());
        untung.hargaBarangKeluar = Double.parseDouble(txtTotalPengeluaran.getText());
        txtTotal.setText(Double.toString(untung.Keuntungan()));
//        
        
    }//GEN-LAST:event_btnTOTALActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtnamabarang.setText("");
        txtPemasukan.setText("");
        txtBarangKeluar.setText("");
        txtTotalPengeluaran.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnLogActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        // Menampilkan pesan dialog bahwa data telah ditambahkan ke tabel
        JOptionPane.showMessageDialog(null, "Data anda Ditambahkan Ke tabel");
        // Mengambil model data dari tabel
        DefaultTableModel dataModel = (DefaultTableModel) tabel_data_laporanbarang.getModel();
        // Inisialisasi sebuah ArrayList bernama 'list'
        List list = new ArrayList<>();
        // Mengatur tabel untuk membuat kolom dari model secara otomatis
        tabel_data_laporanbarang.setAutoCreateColumnsFromModel(true);
        // Membuat instance dari kelas Pembayaran_kasir
        Pembayaran_kasir obj = new Pembayaran_kasir();
         obj.namaBarang = txtnamabarang.getText();
        // Mengatur data barangmasuk menggunakan nilai dari komponen txtPemasukan
        obj.barangmasuk = Double.parseDouble(txtPemasukan.getText());
        // Mengatur data barangkeluar menggunakan nilai dari komponen txtBarangKeluar
        obj.barangKeluar= Double.parseDouble(txtBarangKeluar.getText());
        // Mengatur data TotalPengeluaran menggunakan nilai dari komponen txtTotalPengeluaran
        obj.hargaBarangKeluar = Double.parseDouble(txtTotalPengeluaran.getText());
       obj.TotalKeuntungan = Double.parseDouble(txtTotal.getText());
       
        member mem = new member(75000);
        mem.semen = Double.parseDouble(txt_dataBarang.getText());
        mem.total = Double.parseDouble(txt_totaldata.getText());
        
       
        // Menambahkan data-data dari objek obj ke dalam ArrayList 'list'
        list.add(obj.namaBarang);
        list.add(obj.barangmasuk);
        list.add(obj.barangKeluar);
        list.add(obj.hargaBarangKeluar);
        list.add(obj.TotalKeuntungan);
        list.add(mem.semen);
        list.add(mem.total);
        
        // Menambahkan baris baru ke model tabel menggunakan data dari ArrayList 'list'
        dataModel.addRow(list.toArray());
        //  insert();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) tabel_data_laporanbarang.getModel();
        int rowCount= dataModel.getRowCount();
        while (rowCount > 0){
            dataModel.removeRow(rowCount - 1 );
            rowCount= dataModel.getRowCount(); // update
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnDATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDATAActionPerformed
        // TODO add your handling code here:
        member mem = new member(100);
        mem.semen = Double.parseDouble(txt_dataBarang.getText());
        txt_totaldata.setText(Double.toString(mem.barangGudang()));
        String namaBarang = txtnamabarang.getText();
        String Pemasukkan = txtPemasukan.getText();
        String barangKeluar =  txtBarangKeluar.getText();
        String hargaBarang = txt_dataBarang.getText();
        String TotalKeseluruhan = txtTotal.getText();
        String Data_dari_gudang = txt_dataBarang.getText();
        String DataTotalBarang = txt_totaldata.getText();
    }//GEN-LAST:event_btnDATAActionPerformed
        
//    
    private void tabel_data_laporanbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_data_laporanbarangMouseClicked
        // TODO add your handling code here:
//         int tabel = tabel_data_laporanbarang.getSelectedRow();
//        kode1 = tabel_data_laporanbarang.getValueAt(tabel, 0).toString();
//        mk1 = tabel_data_laporanbarang.getValueAt(tabel, 1).toString();
//        dosen1 = tabel_data_laporanbarang.getValueAt(tabel, 2).toString();
//        jmlsks1 =tabel_data_laporanbarang.getValueAt(tabel, 3).toString();
//        itempilih();
    }//GEN-LAST:event_tabel_data_laporanbarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_LaporanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_LaporanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_LaporanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_LaporanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_LaporanBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDATA;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnTOTAL;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btnhapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tabel_data_laporanbarang;
    private javax.swing.JTextField txtBarangKeluar;
    private javax.swing.JTextField txtPemasukan;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalPengeluaran;
    private javax.swing.JTextField txt_dataBarang;
    private javax.swing.JTextField txt_totaldata;
    private javax.swing.JTextField txtnamabarang;
    // End of variables declaration//GEN-END:variables
}
